# Stage 1

FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2

FROM node:24-alpine

RUN addgroup -S app && adduser -S -G app app

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

RUN npm ci --only=production
RUN npm install -g vite
RUN chown -R app:app /usr/local/lib/node_modules /usr/local/bin .

USER app

EXPOSE 4173

CMD ["npm","run","preview","--","--host","0.0.0.0","--port","4173"]
