# Stage 1(Builder stage) - USed to build the packages & app

FROM node:24 AS builder

# This will create a folder app and make it as pwd
WORKDIR /app

# This will copy all the code
COPY . .

# This will install all the packages
RUN npm install

# This will create a folder called /dist
RUN npm run build

# Stage 2(Runner Stage) - Used to run the application from the builder stage

FROM node:24-alpine

WORKDIR /app

# Copy required packages to run application
COPY package*.json ./
COPY --from=builder /app/dist ./dist

# install vite globally
RUN npm install -g vite

CMD ["npm","run","preview","--","--host","0.0.0.0","--port","5137"]
