# Stage 1
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o devboard-backend .

# Stage 2

FROM alpine:3.20

WORKDIR /app

RUN adduser -D -u 10001 app && chown -R app:app /app

COPY --from=builder --chown=app:app /app/devboard-backend ./devboard-backend

USER app

EXPOSE 8080

ENTRYPOINT ["./devboard-backend"]
