kind: Deployment 
apiVersion: apps/v1
metadata:
  name: devboard-backend-deployment
  namespace: devboard
  labels:
    app: devboard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-backend
  template:
    metadata:
      labels:
        app: devboard-backend
    spec:
      containers:
        - name: devboard-backend
          image: rdn51015/devboard-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: devboard-configmap
                  key: BACKEND_PORT
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10