# Goal: To deploy the built images from CI steps once CI workflow is succeeded

name: CD
on :
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy Example ENV to main ENV
        run: cp .env.example .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy the containers with Docker Compose
        run: |
          docker compose pull
          docker compose up -d