# Goal: I have to do SAST for my code

name: Code Quality
# you can call this workflow before/after any other workflow
on:
  workflow_call:

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: frontend

      - name: code linting
        run: npm run lint
        working-directory: frontend
      
      - name: Setup Go 
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'
          go-version-file: ./backend/go.mod
          cache-dependency-path: ./backend/go.sum

      - name: code vetting
        run: go vet
        working-directory: ./backend
        
      - name: go fmt
        run: go fmt
        working-directory: ./backend
