# Goal: Run end -to -end DevSecOps pipeline
name: DevSecOps

on:
  push:
    branches: [main]
jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  docker-scan:
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit
  
  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit
  
  code-test:
    uses: ./.github/workflows/code-test.yml
    secrets: inherit

  docker-push:
    uses: ./.github/workflows/docker-push.yml
    needs: [code-quality, secret-scan, dependency-scan, docker-scan, sonar-scan, code-test]
    secrets: inherit