# Goal: Run end -to -end DevSecOps pipeline
name: DevSecOps

on:
  push:
    branches: [main]
jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  docker-scan:
    uses: ./.github/workflows/docker-scan.yml
    secrets: inherit
  
  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit
  